[project]
name = 'Legidex'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Legidex]
path = 'contracts/Legidex.clar'
clarity_version = 3
epoch = 3.1

[contracts.compliance]
path = 'contracts/compliance.clar'
clarity_version = 3
epoch = 3.1


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
